apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xcloud-platform-stg
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/barrosnetoarthur-cell/xcloud.git
    targetRevision: HEAD
    path: environments/stg
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true