apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-cluster
spec:
  provider:
    vault:
      server: https://vault.safepurelink.com # TODO: ajuste
      # caBundle (opcional): adicione o certificado CA em base64 se o Vault usar CA própria
      # caBundle: "REPLACE_WITH_BASE64_CA"
      path: kv                        # engine KV v2
      version: v2
      auth:
        kubernetes:
          # Usa o JWT do ServiceAccount; não exige token estático aqui
          mountPath: kubernetes       # caminho do auth k8s no Vault
          role: eso                   # role com policy mínima
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
