apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-dns01
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-cluster
  target:
    name: cloudflare-dns01
    creationPolicy: Owner
  data:
    - secretKey: api-token
      remoteRef:
        key: kv/prod/cloudflare/api
        property: apiToken
